version: "3.8"
services:
  app:
    build: ./infra/php
    volumes:
      # webにもappにもどっちにもマウントが必要なの？？ => 必要
      # コメントアウトするとphpinfo.phpが見つからなくなる
      - ./backend:/work

  web:
    image: nginx:1.18-alpine
    ports:
      - 10080:80
    volumes:
      # コメントアウトすると index.htmlもphpinfo.phpも見つからなくなる
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store:
